"""Finite-volume transient core for next-generation HX transients.

The first implemented layer is the geometry-independent coolant temperature
kernel. Geometry adapters and wall/hot-side coupling are added in later work
packages described in docs/solver_design/TRANSIENT_CORE_IMPLEMENTATION_PLAN.md.
"""

from .adapters_helical import (
    HelicalCoolantFilm,
    HelicalCoreGeometry,
    HelicalWallFlux,
    build_helical_core_geometry,
    build_helical_core_geometry_from_solver,
    conductance_from_h,
    coolant_heat_capacity_J_K,
    flow_direction_from_config,
    helical_coolant_film,
    helical_wall_flux,
    wall_heat_capacity_J_K,
)
from .adapters_shelltube import (
    GasStateProvider,
    GasProviderAtTime,
    CoolantPropertyProvider,
    ShellTubeFluidProperties,
    ShellTubeGasState,
    ShellTubeHotGasMarch,
    ShellTubeStepInputDiagnostics,
    ShellTubeShellFilm,
    ShellTubeTransientCoreResult,
    ShellTubeCoreGeometry,
    ShellTubeTubeGasFilm,
    ShellTubeWallFlux,
    build_shelltube_core_geometry,
    build_shelltube_core_geometry_from_solver,
    coolprop_fluid_properties,
    equilibrium_gas_state_provider,
    fpv_gas_state_provider,
    oxygen_gas_state_provider,
    run_shelltube_transient_core,
    shelltube_conductance_from_h,
    shelltube_coolant_heat_capacity_J_K,
    shelltube_flow_direction,
    shelltube_hot_gas_march,
    shelltube_shell_film,
    shelltube_step_inputs,
    shelltube_tube_gas_film,
    shelltube_wall_flux,
    shelltube_wall_heat_capacity_J_K,
)
from .coolant_fv import CoolantStepResult, implicit_upwind_step
from .compressible_coolant import (
    CompressibleCoolantStepResult,
    CoolantThermodynamicState,
    conservative_mass_energy_step,
    enforce_density_bounds,
    enforce_internal_energy_bounds,
    coolprop_state_from_mass_energy,
    enforce_internal_energy_floor,
    initial_mass_energy_from_TP,
    quasi_steady_face_mdot,
)
from .diagnostics import (
    EnergyAudit,
    TimescaleAudit,
    energy_audit,
    residence_time_s,
    timescale_audit,
    wall_time_constant_s,
)
from .grid import AxialGrid
from .integrator import (
    WallCoolantIntegrationResult,
    WallCoolantStepInputs,
    fixed_time_grid,
    integrate_wall_coolant_fixed_step,
)
from .schedules import (
    collect_transient_schedule_times,
    interp_schedule,
    schedule_times,
)
from .state import TransientState, TransientStateLayout
from .wall_coolant import WallCoolantStepResult, implicit_wall_coolant_step
from .wall_compressible_coolant import (
    WallCompressibleCoolantStepResult,
    semi_implicit_wall_compressible_coolant_step,
)

__all__ = [
    "AxialGrid",
    "CoolantStepResult",
    "CoolantPropertyProvider",
    "CompressibleCoolantStepResult",
    "CoolantThermodynamicState",
    "EnergyAudit",
    "GasStateProvider",
    "GasProviderAtTime",
    "HelicalCoolantFilm",
    "HelicalCoreGeometry",
    "HelicalWallFlux",
    "ShellTubeCoreGeometry",
    "ShellTubeFluidProperties",
    "ShellTubeGasState",
    "ShellTubeHotGasMarch",
    "ShellTubeShellFilm",
    "ShellTubeStepInputDiagnostics",
    "ShellTubeTubeGasFilm",
    "ShellTubeTransientCoreResult",
    "ShellTubeWallFlux",
    "TransientState",
    "TransientStateLayout",
    "TimescaleAudit",
    "WallCoolantIntegrationResult",
    "WallCoolantStepResult",
    "WallCoolantStepInputs",
    "WallCompressibleCoolantStepResult",
    "build_helical_core_geometry",
    "build_helical_core_geometry_from_solver",
    "build_shelltube_core_geometry",
    "build_shelltube_core_geometry_from_solver",
    "coolprop_fluid_properties",
    "equilibrium_gas_state_provider",
    "fpv_gas_state_provider",
    "oxygen_gas_state_provider",
    "quasi_steady_face_mdot",
    "run_shelltube_transient_core",
    "collect_transient_schedule_times",
    "conductance_from_h",
    "conservative_mass_energy_step",
    "coolant_heat_capacity_J_K",
    "coolprop_state_from_mass_energy",
    "enforce_density_bounds",
    "enforce_internal_energy_bounds",
    "enforce_internal_energy_floor",
    "energy_audit",
    "fixed_time_grid",
    "flow_direction_from_config",
    "helical_coolant_film",
    "helical_wall_flux",
    "implicit_upwind_step",
    "implicit_wall_coolant_step",
    "initial_mass_energy_from_TP",
    "integrate_wall_coolant_fixed_step",
    "interp_schedule",
    "residence_time_s",
    "schedule_times",
    "semi_implicit_wall_compressible_coolant_step",
    "shelltube_conductance_from_h",
    "shelltube_coolant_heat_capacity_J_K",
    "shelltube_flow_direction",
    "shelltube_hot_gas_march",
    "shelltube_shell_film",
    "shelltube_step_inputs",
    "shelltube_tube_gas_film",
    "shelltube_wall_flux",
    "shelltube_wall_heat_capacity_J_K",
    "timescale_audit",
    "wall_heat_capacity_J_K",
    "wall_time_constant_s",
]
